### ISSUE TITLE
Broken code example in Running Migrations with Knex blog post

### ISSUE THREAD

**Issue by 3mily** [alexzywiak/alexzywiak.github.io#1]
Hello! There should not be a semi-colon at the end of an item in an array here: https://github.com/alexzywiak/alexzywiak.github.io/blob/master/running-migrations-with-knex/index.html#L197

**Comment by monting** [comment]
@alexzywiak would appreciate if you can push a fix. Thanks for the article!

**Comment by alexzywiak** [comment]
Fixed it.  Thanks for pointing that out.
